//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelClasses
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    
    public partial class ST_Stations_Lots
    {
        public string Lot_Number { get; set; }
        public string Station { get; set; }
        public string Species { get; set; }
        public string Initial_feeding_date { get; set; }
        public string Incubation_Hatchery_Station { get; set; }
        public string First_Hatched_Station { get; set; }
        public string Eggs_Source_Station { get; set; }
        public string Strain { get; set; }
        public string DomesticStatus { get; set; }

        //Method to generate the lot number
        public string generateLotCode()
        {

            String specCode = SpeciesCodeGenerator.getSpeciesCode(Species);
            //Insert the first two inputted letters the strain
            String strain = Strain.Substring(0, 2).ToUpper();
            //If the initial feeding month is December, make next year the feeding cycle year; otherwise make the current year the feeding cycle year
            return specCode + "-" + strain + "-" + DateTime.Parse(Initial_feeding_date).Year + "-" + DomesticStatus.Substring(0, 1).ToUpper() + "-" + StationSymbol.getSymbol(Eggs_Source_Station) + "-" + StationSymbol.getSymbol(Incubation_Hatchery_Station) + "-" + StationSymbol.getSymbol(First_Hatched_Station) + "-" + StationSymbol.getSymbol(Station);
        }
    }


}
